#!/bin/sh
set -eu

. ./xparse/xparse.sh

_TB="$(printf "\t")"
_NL="$(printf "\nx")"
_NL="${_NL%x}"

IFS=

MODE=""
MODE_BUILD="build"
MODE_SEARCH="search"

switch_mode() { # {{{
    local NEW_MODE="${1}"
    if [ -n "${MODE}" ] && [ "${MODE}" != "${NEW_MODE}" ]; then
        printf "[E]: Can't switch operation mode!\n" >&2
        exit 1
    fi

    MODE="${NEW_MODE}"
} # }}}

BUILD_ROOT_DIR=""

SEARCH_CACHE_FILE=""
SEARCH_INCLUDE_TAGS=""
SEARCH_EXCLUDE_TAGS=""
SEARCH_SHOW_TAGS="0"

# Utils {{{

escape_path() { # {{{
    sed -e 's/\\/\\\\/g' \
        -e 's/\t/\\t/g'
} # }}}

unescape_path() { # {{{
    sed -e 's/\\t/\t/g' \
        -e 's/\\\\/\\/g'
} # }}}

# }}}

# Build {{{

do_build_set_root_dir() { # {{{
    switch_mode "${MODE_BUILD}"

    [ -e "${1}" ] || exit 1
    BUILD_ROOT_DIR="${1}"
} # }}}

# }}}

# Search {{{

do_search_set_cache_file() { # {{{
    switch_mode "${MODE_SEARCH}"

    local FILE="${1}"
    [ -e "${FILE}" ] || exit 1
    SEARCH_CACHE_FILE="${FILE}"
} # }}}

do_search_include_tag() { # {{{
    switch_mode "${MODE_SEARCH}"

    local TAG="${1}"
    SEARCH_INCLUDE_TAGS="${SEARCH_INCLUDE_TAGS}${TAG}${_TB}"
} # }}}

do_search_exclude_tag() { # {{{
    switch_mode "${MODE_SEARCH}"

    local TAG="${1}"
    SEARCH_EXCLUDE_TAGS="${SEARCH_EXCLUDE_TAGS}${TAG}${_TB}"
} # }}}

do_search_include_tags() { # {{{
    switch_mode "${MODE_SEARCH}"

    local TAG
    for TAG in "$@"; do
        do_search_include_tag "${TAG}"
    done
} # }}}

do_search_exclude_tags() { # {{{
    switch_mode "${MODE_SEARCH}"

    local TAG
    for TAG in "$@"; do
        do_search_exclude_tag "${TAG}"
    done
} # }}}

do_search_show_tags() { # {{{
    switch_mode "${MODE_SEARCH}"

    SEARCH_SHOW_TAGS="1"
} # }}}

# }}}

# Cache
xparse_add_option  "build_cache"  1  do_build_set_root_dir
xparse_add_option  "b"            1  do_build_set_root_dir

# Search
xparse_add_option  "cache_file"        1  do_search_set_cache_file
xparse_add_option  "c"                 1  do_search_set_cache_file
xparse_add_option  "include"           1  do_search_include_tag
xparse_add_option  "i"                 1  do_search_include_tag
xparse_add_option  "include_multiple" '*' do_search_include_tags
xparse_add_option  "im"               '*' do_search_include_tags
xparse_add_option  "exclude"           1  do_search_exclude_tag
xparse_add_option  "e"                 1  do_search_exclude_tag
xparse_add_option  "exclude_multiple" '*' do_search_exclude_tags
xparse_add_option  "em"               '*' do_search_exclude_tags
xparse_add_option  "show_tags"         0  do_search_show_tags
xparse_add_option  "s"                 0  do_search_show_tags

# File selection
xparse_add_option  "file"   1  do_select_file
xparse_add_option  "f"      1  do_select_file
xparse_add_option  "files" '*' do_select_files
xparse_add_option  "fm"    '*' do_select_files

# Add
xparse_add_option  "tag"   1  do_add_tag
xparse_add_option  "t"     1  do_add_tag
xparse_add_option  "tags" '*' do_add_tags
xparse_add_option  "tm"   '*' do_add_tags

# Remove
xparse_add_option  "del_tag"   1  do_remove_tag
xparse_add_option  "d"         1  do_remove_tag
xparse_add_option  "del_tags" '*' do_remove_tags
xparse_add_option  "dm"       '*' do_remove_tags

xparse_execute_args "$@"

# Args: root dir
build_cache() { # {{{
    # Assumptions:
    # - filenames DON'T contain newlines
    # - tags DON'T contain tabs
    # - tags DON'T contain newlines
    #
    # I think the above assumptions are reasonable, but they can always be
    # escaped later if needed.

    local TAGS_FILE
    IFS=

    find "${BUILD_ROOT_DIR}" -iname '*.tags' -size '+0' | \
        while read -r TAGS_FILE; do
            local FILE="${TAGS_FILE%.tags}"
            [ -e "${FILE}" ] || continue

            # Filename
            printf "${FILE}" | escape_path

            # Tags separated with tabs
            cat "${TAGS_FILE}" | \
                sed -e '/^$/d' | \
                tr '\n' '\t' | \
                sed -e 's/^/\t/' -e 's/$/\n/'
        done
} # }}}

do_search() { # {{{
    local CACHE="$(cat "${SEARCH_CACHE_FILE}")"

    local INC_TAG
    IFS="${_TB}"
    for INC_TAG in ${SEARCH_INCLUDE_TAGS}; do
        CACHE="$(printf "%s\n" "${CACHE}" | grep -F "${_TB}${INC_TAG}${_TB}")"
    done

    local EXC_TAG
    IFS="${_TB}"
    for EXC_TAG in ${SEARCH_EXCLUDE_TAGS}; do
        CACHE="$(printf "%s\n" "${CACHE}" | grep -Fv "${_TB}${EXC_TAG}${_TB}")"
    done

    IFS="${_TB}"
    printf "%s\n" "${CACHE}" | while read -r FILE TAGS; do
        FILE="$(printf "%s" "${FILE}" | unescape_path)"

        if [ "${SEARCH_SHOW_TAGS}" = "0" ]; then
            printf "%s\n" "${FILE}"
        else
            printf "%s\t%s\n" "${FILE}" "${TAGS}"
        fi
    done
} # }}}

case "${MODE}" in
    "${MODE_BUILD}") build_cache ;;
    "${MODE_SEARCH}") do_search ;;
    '*') printf "[E]: Unknown mode\n" >&2
         exit 1 ;;
esac
